export const lang = {
  "az": {
    "l": "Azərbaycan dili",
    "langs": ["azərbaycanca", "ingiliscə", "rusca", "türkcə"],
    "sorting": ["IMDb", "Yeni əlavə edilənlər", "Baxış sayı", "Yeni filmlər"],
    "aboutProject": "Layihə haqqında",
    "feedback": "Əks əlaqə",
    "aboutDev": "Tərtibatçı haqqında",
    "resource": "Resurslar",
    "donate": "Dəstək",
    "player": "İzlə",
    "settings": "Parametrlər",
    "close": "Bağla",
    "info": "Məlumat", 
    "stats": "Əsas məlumatlar",
    "plot": "Məzmun",
    "filter": "Filter",
    "filtering": "Filterlə",
    "film": "film",
    "films": "Filmlər",
    "series": "Seriallar",
    "series_": "serial",
    "syncSub": "Subtitrlərin sinxronizasiyası",
    "next": "Növbəti",
    "prev": "Əvvəlki",
    "dubbing": "Dublyaj",
    "sub": "Subtitr",
    "country": "Ölkə",
    "genre": "Janr",
    "cost": "Büdcə",
    "search": "Axtar",
    "play": "Oxut",
    "pause": "Fasilə ver",
    "volume": "Səs səviyyəsi",
    "fullScreen": "Tam ekran",
    "genres": ["Sənədli film", "Triller", "Dram", "Döyüş", "Fantastika", "Dəhşət", "Macəra", "Melodram", "Komediya", "Müzikl", "Cinayət", "Bioqrafik", "Detektiv", "Ailə", "Tarixi", "Hərbi", "Vestern", "İdman", "Fentezi", "Multiplikasiya", "Musiqi"],
    "countries": ["Azərbaycan", "ABŞ", "BƏƏ", "Avstraliya", "Azərbaycan (SSRİ)", "Honkonq", "İslandiya", "Fransa", "Belçika", "Kanada", "İtaliya", "Norveç", "İspaniya", "Almaniya", "Yaponiya", "SSRİ", "Cənubi Koreya", "Böyük Britaniya", "Çin", "Macarıstan", "Malta", "CAR", "Çexiya", "İsveçrə", "Dominikan Respublikası", "Bolqarıstan", "İsveç", "Litva", "Türkiyə", "Avstriya", "Meksika", "Braziliya", "Yeni Zelandiya", "Kolumbiya", "Argentina", "Niderland", "Uruqvay", "Danimarka", "Rusiya", "Hindistan", "Polşa", "Slovakiya", "Ukrayna", "İrlandiya", "Lüksemburq", "Xorvatiya", "Filippin", "Venesuela", "Əlcəzair", "Qətər", "Ruminiya"],
    "notices": "Nəticələr",
    "genresAs": "%s janrında olan filmlər",
    "countryAs": "%s istehsalı olan filmlər",
    "and": "və",
    "keywords": "filmlər, film izlə, pulsuz, ingilis dili, ingilis dili öyrən, pulsuz",
    "messages": ["Maksimum 5 seçim edə bilərsiniz", "Filmlərin sayı az olduğundan seçimlər arasında  çeşidlənmə \"VƏ YA\" məntiqi əlaqəsi ilə aparılacaq."],
    "rating": "Reytinq",
    "year": "İl",
    "diffF": "Müxtəlif_seqmentlərə_uyğun_çeşidlənmə",
    "sublang": "Subtitr dili",
    "examlang": "İmtahan dili",
    "trlang": "Tərcümə dili",
    "nonS": "Seçilməyib",
    "main": "Əsas səhifə",
    "reset": "Sıfırla",
    "examtype": "İmtahan başlasın",
    "et1": "Timeline ərzində",
    "et2": "Timeline-nın sonunda",
    "aD": 1,
    "aP": 1,
    "nt": "Sorry, content doesn't avaible this language.",
    "eC": "Üzr istəyirik, məzmun hələ hazır deyil.",
    "bT": "Layihədə hər hansı bir qüsur, çatışmazlıq aşkar etmisinizsə, çox xahiş bunu bizə bildirin. Öncədən təşəkkür edirik!",
    "mX": "Bu sahəyə maksimum %s simvol daxil edilməlidir",
    "mN": "Bu sahəyə minimum %s simvol daxil edilməlidir",
    "name": "Adınız",
    "text": "Mətn",
    "contact": "Əlaqə"
  },

  "en": {
    "l": "English",
    "langs": ["azerbaijani", "english", "russian", "turkish"],
    "sorting": ["IMDb", "new added", "view Count", "new movies"],
    "aboutProject": "About Project",
    "feedback": "Report a bug",
    "aboutDev": "About Developer",
    "resource": "Resource",
    "donate": "Donate",
    "player": "Watch",
    "settings": "Settings",
    "close": "Close",
    "info": "Information",
    "stats": "Basic information",
    "plot": "Content",
    "film": "film",
    "filter": "Filter",
    "filtering": "Filtering",
    "films": "Movies",
    "series": "Serials",
    "syncSub": "Synchronization of subtitles",
    "next": "Next",
    "prev": "Previous",
    "dubbing": "Dubbing",
    "sub": "Subtitle",
    "country": "Country",
    "genre": "Genre",
    "cost": "Budget",
    "search": "Search",
    "play": "Play",
    "pause": "Pause",
    "volume": "Volume",
    "examtype": "Start exam",
    "et1": "During timeline",
    "et2": "End timeline",
    "fullScreen": "Full screen",
    "countries": ["Azerbaijan", "USA", "United Arab Emirates", "Australia", "Azerbaijan (USSR)", "Hong Kong", "Iceland", "France", "Belgium", "Canada", "Italy", "Norway" , "Spain", "Germany", "Japan", "USSR", "South Korea", "Great Britain", "China", "Hungary", "Malta", "South Africa", "Czech Republic", "Switzerland", "Dominican Republic", "Bulgaria", "Sweden", "Lithuania", "Turkey", "Austria", "Mexico", "Brazil", "New Zealand", "Colombia", "Argentina", "Netherlands", "Uruguay", "Denmark", "Russia", "India", "Poland", "Slovakia", "Ukraine", "Ireland", "Luxembourg", "Croatia", "Philippines", "Venezuela", "Algeria" , "Qatar", "Romania"],
    "genres": ["Documentary", "Thriller","Drama", "Action", "Fiction", "Horror", "Adventure", "Melodrama", "Comedy", "Musical", "Crime", "Biography", "Detective","History","Family","Western","Military","Sports","Fantasy","Animation","Music"],
    "notices": "Notices",
    "genresAs": "All films in %s genre",
    "countryAs": "All films product of %s",
    "and": "and",
    "keywords": "films, watch, free, english, learn english, subtitle",
    "messages": ["You should select maximum 5 item.", "Filmlərin sayı az olduğundan seçimlər arasında  çeşidlənmə \"VƏ YA\" məntiqi əlaqəsi ilə aparılacaq."],
    "rating": "Rating",
    "year": "Year",
    "diffF": "Sorting by different segments",
    "sublang": "Subtitle language",
    "examlang": "Examming language",
    "nonS": "Non-selected",
    "main": "Main Page",
    "reset": "Reset",
    "trlang": "Tr. language",
    "aD": null,
    "aP": 0,
    "nt": "Sorry, content doesn't avaible this language.",
    "eC": "Sorry, content doesn't ready.",
    "mX": "Maximum %s symbols.",
    "mN": "Minimum %s symbols.",
    "bT": "If you find any bug, please report it to us. Thank you in advance!",
    "name": "Name",
    "text": "Text",
    "contact": "Contact"

  },

  "ru": {
    "l": "Русскый",
    "langs": ["азерб.", "анг.", "рус.", "тур."],
    "sorting": ["IMDb", "новые добавленные", "количество просмотров", "новые фильмы"],
    "aboutProject": "О проекта",
    "feedback": "Сообщить об ошибке",
    "aboutDev": "О автором",
    "resource": "Ресурсы",
    "player": "Смотри",
    "settings": "Параметры",
    "close": "Закрить",
    "info": "Информация",
    "stats": "Главная информация",
    "plot": "Контент",
    "film": "филм",
    "filter": "Филтер",
    "filtering": "Филтерация",
    "films": "Филмы",
    "series": "Сериалы",
    "syncSub": "Синхронизация субт.",
    "next": "Далее",
    "prev": "Назад",
    "dubbing": "Дубляж",
    "sub": "Субтитр",
    "country": "Страна",
    "genre": "Жанр",
    "cost": "Буджет",
    "search": "Поиск",
    "play": "Играть",
    "pause": "Пауза",
    "volume": "Громкость",
    "examtype": "Cтарт экзамена",
    "et1": "В Timeline",
    "et2": "В конце Timeline",
    "film": "фильм",
    "genres": ["Документальный", "Триллер", "Драма", "Боевик", "Фантастика", "Ужасы", "Приключения", "Мелодрама", "Комедия", "Мюзикл", "Криминал", "Биография", "Детектив", "История", "Семейный", "Вестерн", "Военный", "Спорт", "Фэнтези", "Анимация", "Музыка"],
    "countries": ["Азербайджан", "США", "ОАЭ", "Австралия", "Азербайджан (СССР)", "Гонконг", "Исландия", "Франция", "Бельгия", "Канада", "Италия", "Норвегия", "Испания", "Германия", "Япония", "СССР", "Корея Южная", "Великобритания", "Китай", "Венгрия", "Мальта", "ЮАР", "Чехия", "Швейцария", "Доминикана", "Болгария", "Швеция", "Литва", "Турция", "Австрия", "Мексика", "Бразилия", "Новая Зеландия", "Колумбия", "Аргентина", "Нидерланды", "Уругвай", "Дания", "Россия", "Индия", "Польша", "Словакия", "Украина", "Ирландия", "Люксембург", "Хорватия", "Филиппины", "Венесуэла", "Алжир", "Катар", "Румыния"],
    "notices": "Резултаты",
    "genresAs": "Филмы по жанру %s",
    "countryAs": "%s филмы",
    "and": "и",
    "keywords": "фильмы, смотреть фильмы, бесплатно, учить английский, английский, бесплатно",
    "messages": ["Maksimum 5 seçim edə bilərsiniz", "Filmlərin sayı az olduğundan seçimlər arasında  çeşidlənmə \"VƏ YA\" məntiqi əlaqəsi ilə aparılacaq."],
    "rating": "Рейтинг",
    "year": "Года",
    "diffF": "Sorting_by_different_segments",
    "sublang": "Язык субтитры",
    "examlang": "Язык экзамена",
    "nonS": "не выбрано",
    "main": "Главная страница",
    "trlang": "Првд. язык",
    "reset": "Сброс",
    "aD": null,
    "aP": 2,
    "nt": "Этот контент недоступен на русском языке. Вы можете попытаться посмотреть на азербайджанскую версию этой страницы.",
    "eC": "Извините, контент не готов.",
    "mX": "Максимум %s символов.",
    "mN": "Минимум %s символов.",
    "bT": "Если вы обнаружите какую-либо ошибку, пожалуйста, сообщите нам об этом. Заранее благодарю вас!",
    "name": "Имя",
    "text": "Текст",
    "contact": "Контакть"
  },

  "tr": {
    "l": "Türkçe",
    "langs": ["azerbaycanca", "ingilizce", "rusca", "türkce"],
    "sorting": ["IMDb", "yeni eklenen", "görüntüleme sayısı", " yeni filmler"],
    "aboutProject": "Proje hakkında",
    "feedback": "Geri bildirim",
    "aboutDev": "Geliştirici hakkında",
    "resource": "Resource",
    "donate": "Destek",
    "player": "İzle",
    "film": "film",
    "settings": "Ayarlar",
    "close": "Kapat",
    "info": "Bilgi",
    "stats": "Temel bilgiler",
    "plot": "İçerik",
    "filter": "Filtre",
    "filtering": "Filtrele",
    "films": "Filmler",
    "series": "Seri",
    "syncSub": "Altyazıların senkronizasyonu",
    "next": "Next",
    "prev": "Önceki",
    "dubbing": "Dublyaj",
    "sub": "Altyazı",
    "country": "Ülke",
    "genre": "Tür",
    "cost": "Bütçe",
    "search": "Arama",
    "play": "Okut",
    "pause": "Durdur",
    "volume": "Ses",
    "fullScreen": "Tam ekran",
    "countries": ["Azerbaycan", "ABD", "BAE", "Avustralya", "Azerbaycan (SSCB)", "Hong Kong", "İzlanda", "Fransa", "Belçika", "Kanada", "İtalya", "Norveç" , "İspanya", "Almanya", "Japonya", "SSCB", "Güney Kore", "İngiltere", "Çin", "Macaristan", "Malta", "Güney Afrika", "Çek Cumhuriyeti", "İsviçre", "Dominik Cumhuriyeti", "Bulgaristan", "İsveç", "itvanya", "Türkiye", "Avusturya", "Meksika", "Brezilya", "Yeni Zelanda", "Kolombiya", "Arjantin", "Hollanda", "Uruguay", "Danimarka","Rusya", "Hindistan", "Polonya", "Slovakya", "Ukrayna", "İrlanda", "Lüksemburg", "Hırvatistan", "Filippin", "Venezuela", "Cezayir" , "Katar", "Romanya"],
    "genres": ["Belgesel", "Gerilim", "Drama", "Aksiyon", "Kurgu", "Korku", "Macera", "Melodrama", "Komedi", "Müzikal", "Suç", "Biyografi", "Dedektif","Tarih","Aile","Batı","Askeri","Spor","Fantezi","Animasyon","Müzik"],
    "notices": "Neticeler",
    "genresAs": "%s türünde olan filmler",
    "countryAs": "%s istehsali olan filmler",
    "and": "ve",
    "keywords": "filmler, film izle, bedava, ingiliz dili, ingilizce, altyazı",
    "messages": ["Maksimum 5 seçenek işaretlene bilir", "Filmlerin sayı az olduğundan, seçenekler arasında \"VE YA\" mentiq bağlantısına uygun filtreleme yapılacak."],
    "rating": "Değerlendirme",
    "year": "Yıl",
    "diffF": "Çeşitli_segmentlere_uygun_filtreleme",
    "sublang": "Subtitr dili",
    "examlang": "Sınav dili",
    "trlang": "Çeviri dili",
    "examtype": "Sınav baş. tipi",
    "et1": "Timeline erzinde",
    "et2": "Timeline'nın sonunda",
    "nonS": "Seçim yapılmayıb",
    "main": "Ana sayfa",
    "reset": "Sıfırla",
    "aD": null,
    "aP": 3,
    "nt": "Üzgünüz, içerik henüz bu dilde mevcut değil",
    "eC": "Üzgünüz, içerik henüz hazır değil.",
    "mX": "Maksimum %s işaret içere bilir.",
    "mN": "Minimum %s işaret içermelidir.",
    "bT": "Rica ederiz, projede gördüğünüz hataları bize bildirin. Önceden teşekkür ederiz!",
    "name": "Adınız",
    "text": "Metn",
    "contact": "İletişim"
  }


}
